# Used by run script to make sure builds are done using builder container
# This is the same container used by GitHub action actions/sisdel/builder

version: '2'
services:
    builder:
        build:
            context: builder
        volumes:
        - ${srcroot}:${srcroot}:ro
        - ${buildroot}:${buildroot}:rw
        working_dir: ${buildroot}
        user: ${uid}:${gid}

