version: '2'
services:
    do:
        build:
            context: .
            args:
            - buildroot
        volumes:
        - ${srcroot}:${srcroot}:ro
        - ${buildroot}:${buildroot}:rw
        working_dir: ${buildroot}
        user: ${uid}:${gid}

