#!/usr/bin/env bash
set -xeEuo pipefail

readonly srcroot=$(dirname $0)
readonly buildroot=$(pwd)
readonly uid=$(id -u)
readonly gid=$(id -g)

export srcroot buildroot uid gid

case "$1" in
    compose) ( cd "${srcroot}" && docker-compose build ) && exit 0;;
    config)  cmd=( cmake -G "Ninja Multi-Config" "${srcroot}" );;
    release) cmd=( cmake --build . --config Release );;
    debug)   cmd=( cmake --build . --config Debug );;
    build)   cmd=( cmake --build . );;
    doc)     cmd=( cmake --build . --target doc );;
    install) cmd=( cmake --install . );;
    custom)  cmd=( );;
    *)       printf '%s: Unknown command, must be one of: compose config build release debug doc install'; exit 1;;
esac
shift

(( $# == 0 )) || cmd+=( "$@" )

( cd "${srcroot}" && docker-compose run builder "${cmd[@]}" )

