/*
  Copyright (C) 2017 Mats G. Liljegren
  SPDX-License-Identifier: Apache-2.0

  This file is part of Sisdel.

  Licensed under the Apache License, Version 2.0 (the "License"); you may not
  use this file except in compliance with the License. You may obtain a copy
  of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations
  under the License.
*/

// Header file generated by the build system based from the template file
// config.hh.in.
#include "config.hh"

// Stop lint from complaining on unused string.
#ifndef lint

/**
 * Declare what string.
 * The what string makes it possible to determine what source code that
 * built the binary.
 */
extern const char what_str[];
const char what_str[] = "@(#)Sisdel v" STR(SISDEL_VERSION_MAJOR) "." STR(SISDEL_VERSION_MINOR) ", branch " STR(SISDEL_GIT_BRANCH) ", commit " STR(SISDEL_GIT_COMMIT_HASH);
#endif /* lint */
