---

on:
  push:
  pull_request:
jobs:
#  lint:
#    name: lint
#    runs-on: ubuntu-latest
#    steps:
#    - id: checkout
#      name: checkout source
#      uses: actions/checkout@v2
#      with:
#        fetch-depth: 0
#    - id: super-lint
#      name: super-lint
#      uses: github/super-linter@v3
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        VALIDATE_SHELL_SHFMT: false
#    - id: c-lint
#      name: c-linter
#      uses: ArtificialAmateur/cpp-linter-action@0.01
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
      name: build Sisdel
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
            with:
                path: 'src'
                fetch-depth: 0
          - uses: ./src/builder
            with:
                cmdline: 'cmake -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE="\${CONAN_USER_HOME}/conan_paths.cmake" src'
          - uses: ./src/builder
            with:
                cmdline: cmake --build . --target Release
          - uses: ./src/builder
            with:
                cmdline: cmake --build . --target Debug
          - uses: ./src/builder
            with:
                cmdline: cmake --build . --target Doc
          - id: upload-artifacts
            name: upload artifacts
            uses: actions/upload-artifact@v2
            with:
                name: sisdel-binaries
                path: sisdel-*
                if-no-files-found: error

